# https://www.comet.ml

comet:
  _target_: lightning.pytorch.loggers.comet.CometLogger
  api_key: ${oc.env:COMET_API_TOKEN} # APIキーは環境変数から読み込まれます
  save_dir: "${paths.output_dir}"
  project_name: "lightning-hydra-template"
  rest_api_key: null
  # experiment_name: ""
  experiment_key: null # 実験を再開するために設定
  offline: False
  prefix: ""