# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.RichModelSummary.html

model_summary:
  _target_: lightning.pytorch.callbacks.RichModelSummary
  max_depth: 1 # 要約に含まれるレイヤーのネスト（入れ子）の最大深度